use serde::{Deserialize, Serialize};

/// The static version list schema. Generated by `catalog-gen` (GitHub Actions)
/// and embedded into the binary. It intentionally contains NO concrete download
/// links — those are resolved live at download time.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Catalog {
    pub generated_at: String,
    #[serde(default)]
    pub windows: Vec<WindowsVersion>,
    #[serde(default)]
    pub linux: Vec<LinuxDistro>,
    #[serde(default)]
    pub tools: Vec<Tool>,
}

// ---------------------------------------------------------------------------
// Windows (Fido-style: version -> release -> edition -> productEditionId)
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct WindowsVersion {
    pub name: String,
    pub slug: String,
    #[serde(default)]
    pub releases: Vec<WindowsRelease>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct WindowsRelease {
    pub release: String,
    #[serde(default)]
    pub editions: Vec<WindowsEdition>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct WindowsEdition {
    /// Display name, e.g. "Windows 11 Home/Pro/Edu".
    pub name: String,
    /// Aliases, e.g. ["desktop"].
    #[serde(default)]
    pub types: Vec<String>,
    /// Microsoft productEditionId(s) for this edition.
    #[serde(default)]
    pub product_edition_id: Vec<u64>,
}

// ---------------------------------------------------------------------------
// Linux (versions from endoflife.date; no download links)
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct LinuxDistro {
    pub name: String,
    pub slug: String,
    /// template | proxmox | nixos | release-page
    pub resolver: String,
    /// Rendered at download time with {version}, {cycle}, {arch}.
    pub url_template: Option<String>,
    /// Official download/release page (for release-page resolver).
    pub page_url: Option<String>,
    #[serde(default)]
    pub arch: Vec<String>,
    #[serde(default)]
    pub cycles: Vec<LinuxCycle>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct LinuxCycle {
    pub cycle: String,
    pub latest: Option<String>,
    pub lts: Option<bool>,
    pub release_date: Option<String>,
    pub eol: Option<String>,
}

// ---------------------------------------------------------------------------
// Tools / rescue (GitHub releases style)
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Tool {
    pub name: String,
    pub slug: String,
    pub repo: Option<String>,
    /// Rendered at download time with {tag}, {release}.
    pub url_template: Option<String>,
    #[serde(default)]
    pub arch: Vec<String>,
    #[serde(default)]
    pub cycles: Vec<ToolCycle>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct ToolCycle {
    pub tag: String,
    pub release: Option<String>,
}
