use crate::error::{Error, Result};

pub use crate::catalog_schema::*;

/// The static version list, generated by `catalog-gen` (GitHub Actions) and
/// embedded into the binary. It intentionally contains NO concrete download
/// links — those are resolved live at download time.
pub const EMBEDDED_CATALOG: &str = include_str!("../catalog.json");

impl Catalog {
    /// Parse the embedded catalog.
    pub fn load() -> Result<Catalog> {
        serde_json::from_str(EMBEDDED_CATALOG)
            .map_err(|e| Error::Parse(format!("embedded catalog.json: {e}")))
    }

    pub fn search(&self, kind: Option<Kind>, query: Option<&str>) -> Vec<SystemMatch> {
        let q = query.unwrap_or("");
        let mut out = Vec::new();
        if kind.is_none() || kind == Some(Kind::Windows) {
            for v in &self.windows {
                if matches_query(&v.name, &v.slug, q) {
                    out.push(SystemMatch::windows(v));
                }
            }
        }
        if kind.is_none() || kind == Some(Kind::Linux) {
            for d in &self.linux {
                if matches_query(&d.name, &d.slug, q) {
                    out.push(SystemMatch::linux(d));
                }
            }
        }
        if kind.is_none() || kind == Some(Kind::Tools) {
            for t in &self.tools {
                if matches_query(&t.name, &t.slug, q) {
                    out.push(SystemMatch::tools(t));
                }
            }
        }
        out
    }
}

fn matches_query(name: &str, slug: &str, query: &str) -> bool {
    if query.is_empty() {
        return true;
    }
    let q = query.to_lowercase();
    name.to_lowercase().contains(&q) || slug.to_lowercase().contains(&q)
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Kind {
    Windows,
    Linux,
    Tools,
}

impl Kind {
    pub fn as_str(&self) -> &'static str {
        match self {
            Kind::Windows => "windows",
            Kind::Linux => "linux",
            Kind::Tools => "tools",
        }
    }
}

/// A search hit, denormalized for display.
#[derive(Debug, Clone)]
pub struct SystemMatch {
    pub kind: Kind,
    pub name: String,
    pub slug: String,
    pub versions: Vec<String>,
    pub detail: String,
}

impl SystemMatch {
    fn windows(v: &WindowsVersion) -> Self {
        let versions = v
            .releases
            .iter()
            .map(|r| r.release.clone())
            .collect::<Vec<_>>();
        Self {
            kind: Kind::Windows,
            name: v.name.clone(),
            slug: v.slug.clone(),
            versions,
            detail: "Windows ISO (Microsoft connector)".to_string(),
        }
    }

    fn linux(d: &LinuxDistro) -> Self {
        let versions = d
            .cycles
            .iter()
            .map(|c| {
                let lts = if c.lts.unwrap_or(false) { " (LTS)" } else { "" };
                match &c.latest {
                    Some(latest) if !latest.is_empty() => {
                        format!("{}{} [{}]", c.cycle, lts, latest)
                    }
                    _ => format!("{}{}", c.cycle, lts),
                }
            })
            .collect::<Vec<_>>();
        Self {
            kind: Kind::Linux,
            name: d.name.clone(),
            slug: d.slug.clone(),
            versions,
            detail: format!("{} resolver", d.resolver),
        }
    }

    fn tools(t: &Tool) -> Self {
        let versions = t
            .cycles
            .iter()
            .map(|c| {
                c.release
                    .as_ref()
                    .map(|r| format!("{} ({})", c.tag, r))
                    .unwrap_or_else(|| c.tag.clone())
            })
            .collect::<Vec<_>>();
        Self {
            kind: Kind::Tools,
            name: t.name.clone(),
            slug: t.slug.clone(),
            versions,
            detail: t
                .repo
                .as_ref()
                .map(|r| format!("GitHub releases: {r}"))
                .unwrap_or_default(),
        }
    }
}
